version: "3.9"
services:
  apache:
    build:
      context: './apache/'
      args:
       PHP_VERSION: "8.0"
       DOMAIN_TEMPLATE: "petelocal.net"
       OS_VERSION: "amd64/ubuntu:focal"
       MOD_SECURITY: "Off"
       SERVER_STATUS: "On"
    depends_on:
      - mariadb
    environment:
      DB_HOST: mysql
    networks:
      - backend
    ports:
      - "80:80"
    volumes:
      - ./public_html:/var/www/html
      - ./conf:/etc/apache2/pete-sites
      - ./ssh:/var/www/.ssh
    container_name: apache
  mariadb:
      image: "amd64/mariadb:10.6"
      restart: 'always'
      ports:
        - "3306:3306"
      networks:
        - backend
      volumes: 
        - my-datavolume:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: rootpassword
        MYSQL_DATABASE: pete_db
        MYSQL_USER: otherUser
        MYSQL_PASSWORD: password
      container_name: mysql
  phpmyadmin:
    depends_on:
      - mariadb
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    links:
      - "mariadb"
    environment:
      PMA_HOST: "mysql"
      PMA_PORT: "3306"
      UPLOAD_LIMIT: "256M"
      container_name: phpmyadmin
    networks:
      - backend
networks:
  backend:
volumes:
    my-datavolume:
