#ARG MYSQL_VERSION
FROM mysql:5.7

RUN mkdir -p /data/application

#RUN sed -ire 's/max_allowed_packet.*=.*/max_allowed_packet = 32505856/g' /etc/mysql/my.cnf
#RUN echo "max_allowed_packet=32505856" >> /etc/mysql/my.cnf